jobs:
  scan:
    runs-on: ubuntu-latest
    # use the prod environment, where the secret CAST_HIGHLIGHT_API_TOKEN is defined
    environment: prod

 

    steps:
      - uses: actions/checkout@v2

 

      - name: get company and application ids
        run: |
          cat .github/workflows/hl.env >> $GITHUB_ENV

 

      - name: scan project source code 
        run: |
          docker run --rm -v $(pwd):/s -v /tmp:/w  casthighlight/hl-agent-cli \
                                                   --sourceDir /s \
                                                   --workingDir /w \
                                                   --tokenAuth ${{ secrets.CAST_HIGHLIGHT_API_TOKEN }} \
                                                   --companyId ${{ env.companyId }} \
                                                   --applicationId ${{ env.applicationId }} \
                                                   --serverUrl ${{ env.serverUrl }} \
                                                   --ignoreDirectories ${{ env.ignoreDirectories }}
